#!/usr/bin/env -S npx tsx
/**
 * Real connectivity smoke test for IBM watsonx.ai.
 *
 * Unlike tests/unit/lib/watsonx.test.ts (which mocks the SDK), this script
 * talks to your ACTUAL watsonx.ai project — it proves the credentials in
 * backend/.env actually work, not just that the code is correct.
 *
 * Run from the backend/ directory:
 *   pnpm run test:watsonx-connectivity
 *
 * Requires backend/.env to exist and be populated — generate it from the
 * root .env with `pnpm run env:sync` (see docs/ENV-VARS.md).
 */
import * as fs from 'node:fs'
import * as path from 'node:path'

// backend/.env is gitignored and generated by scripts/sync-env.js — load it
// manually here since this script runs standalone, outside the Express app.
function loadBackendEnv(): void {
  const envPath = path.resolve(__dirname, '..', '.env')
  if (!fs.existsSync(envPath)) {
    console.error(
      '\x1b[31mNo backend/.env found.\x1b[0m Run `pnpm run env:sync` from the repo root first ' +
        '(after filling in the WATSONX_AI_* values in the root .env — see docs/ENV-VARS.md).',
    )
    process.exit(1)
  }
  for (const line of fs.readFileSync(envPath, 'utf8').split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const eq = trimmed.indexOf('=')
    if (eq === -1) continue
    const key = trimmed.slice(0, eq).trim()
    const value = trimmed.slice(eq + 1).trim()
    if (!process.env[key]) process.env[key] = value
  }
}

loadBackendEnv()

async function main() {
  // Imported after env is loaded, since watsonx.ts reads process.env lazily on first call.
  const { listFoundationModelIds, generateText } = await import('../src/lib/watsonx')

  console.log(`watsonx.ai URL: ${process.env.WATSONX_AI_URL}`)
  console.log(`Project id:     ${process.env.WATSONX_AI_PROJECT_ID}\n`)

  try {
    console.log('1. Listing available foundation models (proves IAM auth works)...')
    const modelIds = await listFoundationModelIds()
    if (modelIds.length === 0) {
      throw new Error('watsonx.ai returned zero foundation models — unexpected for a healthy instance')
    }
    console.log(`   ✔ Auth succeeded — ${modelIds.length} models visible`)

    console.log('2. Generating text (proves inference + project id work)...')
    const output = await generateText('Reply with exactly one word: connected')
    console.log(`   ✔ Generation succeeded — model replied: "${output.trim()}"`)

    console.log('\n✅ watsonx.ai connectivity check passed.')
  } catch (error) {
    console.error('\n❌ watsonx.ai connectivity check failed:')
    console.error(error instanceof Error ? error.message : error)
    console.error(
      '\nCommon causes: wrong WATSONX_AI_URL region, API key not entitled to watsonx.ai, ' +
        'WATSONX_AI_PROJECT_ID not associated with a Watson Machine Learning instance, or the ' +
        'default model id no longer available in your region (override with WATSONX_AI_MODEL_ID).',
    )
    process.exitCode = 1
  }
}

void main()
