#!/usr/bin/env -S npx tsx
/**
 * Real connectivity smoke test for IBM Cloud Object Storage.
 *
 * Unlike tests/unit/lib/objectStorage.test.ts (which mocks the SDK), this
 * script talks to your ACTUAL bucket — it proves the credentials in
 * backend/.env actually work, not just that the code is correct.
 *
 * Run from the backend/ directory:
 *   pnpm run test:cos-connectivity
 *
 * Requires backend/.env to exist and be populated — generate it from the
 * root .env with `pnpm run env:sync` (see docs/ENV-VARS.md).
 */
import * as fs from 'node:fs'
import * as path from 'node:path'

// backend/.env is gitignored and generated by scripts/sync-env.js — load it
// manually here since this script runs standalone, outside the Express app.
function loadBackendEnv(): void {
  const envPath = path.resolve(__dirname, '..', '.env')
  if (!fs.existsSync(envPath)) {
    console.error(
      '\x1b[31mNo backend/.env found.\x1b[0m Run `pnpm run env:sync` from the repo root first ' +
        '(after filling in the COS_* values in the root .env — see docs/ENV-VARS.md).',
    )
    process.exit(1)
  }
  for (const line of fs.readFileSync(envPath, 'utf8').split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const eq = trimmed.indexOf('=')
    if (eq === -1) continue
    const key = trimmed.slice(0, eq).trim()
    const value = trimmed.slice(eq + 1).trim()
    if (!process.env[key]) process.env[key] = value
  }
}

loadBackendEnv()

async function main() {
  // Imported after env is loaded, since objectStorage.ts reads process.env lazily on first call.
  const { uploadObject, getObject, deleteObject } = await import('../src/lib/objectStorage')

  const testKey = `connectivity-test/${Date.now()}.txt`
  const testContent = `Object Storage connectivity test — ${new Date().toISOString()}`

  console.log(`Bucket:  ${process.env.COS_BUCKET_NAME}`)
  console.log(`Test key: ${testKey}\n`)

  try {
    console.log('1. Uploading test object...')
    await uploadObject(testKey, testContent, 'text/plain')
    console.log('   ✔ Upload succeeded')

    console.log('2. Retrieving test object...')
    const retrieved = await getObject(testKey)
    const retrievedText = retrieved.toString('utf8')
    if (retrievedText !== testContent) {
      throw new Error(
        `Retrieved content does not match what was uploaded.\n  Expected: ${testContent}\n  Got:      ${retrievedText}`,
      )
    }
    console.log('   ✔ Retrieval succeeded and content matches')

    console.log('3. Cleaning up test object...')
    await deleteObject(testKey)
    console.log('   ✔ Delete succeeded')

    console.log('\n✅ Object Storage connectivity check passed.')
  } catch (error) {
    console.error('\n❌ Object Storage connectivity check failed:')
    console.error(error instanceof Error ? error.message : error)
    console.error(
      '\nCommon causes: wrong COS_ENDPOINT region, API key not tied to this instance, ' +
        'bucket name typo, or the bucket/instance not fully provisioned yet.',
    )
    process.exitCode = 1
  }
}

void main()
