#!/usr/bin/env -S npx tsx
/**
 * Real connectivity smoke test for IBM Cloudant.
 *
 * Unlike a mocked unit test, this script talks to your ACTUAL Cloudant
 * instance — it proves the credentials in backend/.env actually work, not
 * just that the code is correct.
 *
 * Run from the backend/ directory:
 *   pnpm run test:cloudant-connectivity
 *
 * Requires backend/.env to exist and be populated — generate it from the
 * root .env with `pnpm run env:sync` (see docs/ENV-VARS.md).
 */
import * as fs from 'node:fs'
import * as path from 'node:path'

// backend/.env is gitignored and generated by scripts/sync-env.js — load it
// manually here since this script runs standalone, outside the Express app.
function loadBackendEnv(): void {
  const envPath = path.resolve(__dirname, '..', '.env')
  if (!fs.existsSync(envPath)) {
    console.error(
      '\x1b[31mNo backend/.env found.\x1b[0m Run `pnpm run env:sync` from the repo root first ' +
        '(after filling in the CLOUDANT_* values in the root .env — see docs/ENV-VARS.md).',
    )
    process.exit(1)
  }
  for (const line of fs.readFileSync(envPath, 'utf8').split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const eq = trimmed.indexOf('=')
    if (eq === -1) continue
    const key = trimmed.slice(0, eq).trim()
    const value = trimmed.slice(eq + 1).trim()
    if (!process.env[key]) process.env[key] = value
  }
}

loadBackendEnv()

async function main() {
  // Imported after env is loaded, since cloudant.ts reads process.env lazily on first call.
  const { ensureDatabase, putDocument, getDocument, deleteDocument } = await import(
    '../src/lib/cloudant'
  )

  const testDb = 'connectivity-test'
  const testDocId = `check-${Date.now()}`
  const testContent = {
    message: 'Cloudant connectivity test',
    timestamp: new Date().toISOString(),
  }

  console.log(`Cloudant URL: ${process.env.CLOUDANT_URL}`)
  console.log(`Test doc:     ${testDb}/${testDocId}\n`)

  try {
    console.log('1. Ensuring test database exists...')
    await ensureDatabase(testDb)
    console.log('   ✔ Database ready')

    console.log('2. Writing test document...')
    const rev = await putDocument(testDb, { _id: testDocId, ...testContent })
    console.log('   ✔ Write succeeded')

    console.log('3. Retrieving test document...')
    const retrieved = await getDocument(testDb, testDocId)
    if (retrieved.message !== testContent.message) {
      throw new Error(
        `Retrieved content does not match what was written.\n  Expected: ${JSON.stringify(testContent)}\n  Got:      ${JSON.stringify(retrieved)}`,
      )
    }
    console.log('   ✔ Retrieval succeeded and content matches')

    console.log('4. Cleaning up test document...')
    await deleteDocument(testDb, testDocId, (retrieved._rev as string) ?? rev)
    console.log('   ✔ Delete succeeded')

    console.log('\n✅ Cloudant connectivity check passed.')
  } catch (error) {
    console.error('\n❌ Cloudant connectivity check failed:')
    console.error(error instanceof Error ? error.message : error)
    console.error(
      '\nCommon causes: wrong CLOUDANT_URL region/instance, API key not tied to this ' +
        'instance, or the instance not fully provisioned yet.',
    )
    process.exitCode = 1
  }
}

void main()
