#!/usr/bin/env -S npx tsx
/**
 * Real connectivity smoke test for Firebase (Auth + Firestore).
 *
 * This talks to the ACTUAL Firebase project configured in backend/.env — it
 * proves the service account key and project id actually work, not just
 * that the code compiles.
 *
 * Run from the backend/ directory:
 *   pnpm run test:firebase-connectivity
 *
 * Requires backend/.env to exist and be populated — generate it from the
 * root .env with `pnpm run env:sync` (see docs/ENV-VARS.md).
 */
import * as fs from 'node:fs'
import * as path from 'node:path'

// backend/.env is gitignored and generated by scripts/sync-env.js — load it
// manually here since this script runs standalone, outside the Express app.
function loadBackendEnv(): void {
  const envPath = path.resolve(__dirname, '..', '.env')
  if (!fs.existsSync(envPath)) {
    console.error(
      '\x1b[31mNo backend/.env found.\x1b[0m Run `pnpm run env:sync` from the repo root first ' +
        '(after filling in the FIREBASE_* values in the root .env — see docs/ENV-VARS.md).',
    )
    process.exit(1)
  }
  for (const line of fs.readFileSync(envPath, 'utf8').split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const eq = trimmed.indexOf('=')
    if (eq === -1) continue
    const key = trimmed.slice(0, eq).trim()
    const value = trimmed.slice(eq + 1).trim()
    if (!process.env[key]) process.env[key] = value
  }
}

loadBackendEnv()

async function main() {
  // Imported after env is loaded, since firebase.ts initializes the admin
  // app eagerly at module-load time (reads process.env immediately).
  const { adminAuth, adminDb } = await import('../src/lib/firebase')

  const testCollection = 'connectivity-test'
  const testDocId = `check-${Date.now()}`
  const testContent = {
    message: 'Firebase connectivity test',
    timestamp: new Date().toISOString(),
  }

  console.log(`Project:  ${process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID}`)
  console.log(`Test doc: ${testCollection}/${testDocId}\n`)

  try {
    console.log('1. Writing test document to Firestore...')
    await adminDb.collection(testCollection).doc(testDocId).set(testContent)
    console.log('   ✔ Write succeeded')

    console.log('2. Retrieving test document...')
    const snapshot = await adminDb.collection(testCollection).doc(testDocId).get()
    const retrieved = snapshot.data()
    if (!retrieved || retrieved.message !== testContent.message) {
      throw new Error(
        `Retrieved content does not match what was written.\n  Expected: ${JSON.stringify(testContent)}\n  Got:      ${JSON.stringify(retrieved)}`,
      )
    }
    console.log('   ✔ Retrieval succeeded and content matches')

    console.log('3. Cleaning up test document...')
    await adminDb.collection(testCollection).doc(testDocId).delete()
    console.log('   ✔ Delete succeeded')

    console.log('4. Checking Firebase Auth admin access...')
    await adminAuth.listUsers(1)
    console.log('   ✔ Auth admin API reachable')

    console.log('\n✅ Firebase connectivity check passed.')
  } catch (error) {
    console.error('\n❌ Firebase connectivity check failed:')
    console.error(error instanceof Error ? error.message : error)
    console.error(
      '\nCommon causes: wrong/expired service account key, project id mismatch, ' +
        'Firestore not enabled on the project, or the service account missing permissions.',
    )
    process.exitCode = 1
  }
}

void main()
